spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: crm
          uri: lb://crm-service
          predicates:
            - Path=/api/crm/**
        - id: production
          uri: lb://production-service
          predicates:
            - Path=/api/production/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
