spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: crm
          uri: lb://crm-service
          predicates:
            - Path=/api/crm/**
        - id: production
          uri: lb://production-service
          predicates:
            - Path=/api/production/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: stock
          uri: lb://stock-service
          predicates:
            - Path=/api/stock/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
